# Generated by Django 5.0.1 on 2024-02-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0002_espece_nom_scientifique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='espece',
            name='statut',
            field=models.CharField(choices=[('DISPARU', 'En voie de disparition'), ('DANGER', 'En danger'), ('PROTEGE', 'Protégé'), ('INCONNU', 'On sait pas!')], default='INCONNU', max_length=250),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateTimeField()),
                ('quantite', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('notes', models.TextField(default='Pas de notes')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='faunatrack/medias/observations_photos/')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='faunatrack.espece')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('ACT', 'PROJET_ACTIF'), ('INACT', 'PROJET_INACTIF')], default='INACT', max_length=15)),
                ('observations', models.ManyToManyField(related_name='projets', to='faunatrack.observation')),
            ],
        ),
        migrations.CreateModel(
            name='Scientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=250, null=True)),
                ('Institution', models.CharField(blank=True, default='CNRS', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scientifique', to=settings.AUTH_USER_MODEL, verbose_name='Profil Scientifique')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='scientifique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation', to='faunatrack.scientifique'),
        ),
    ]
