# Generated by Django 5.0.1 on 2024-02-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0003_espece_statut_observation_project_scientifique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='observations',
            field=models.ManyToManyField(null=True, related_name='projets', to='faunatrack.observation'),
        ),
    ]
