# Generated by Django 5.0.1 on 2024-02-06 14:05

import django.core.validators
import faunatrack.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0004_alter_project_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[faunatrack.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(limit_value=180), django.core.validators.MinValueValidator(limit_value=-180)]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='faunatrack/static/observations_photos/'),
        ),
    ]
