# Generated by Django 5.0.1 on 2024-02-07 09:18

import faunatrack.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0006_alter_observation_date_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text="je suis l'aide", max_digits=9, validators=[faunatrack.validators.validate_latitude]),
        ),
    ]
